print ("")
print ("hostname: ")
h = input()
print ("username: ")
u = input()
print ("password: ")
p = input()
print ("database: ")
d = input()
a = open("conexao.json",mode="w")
a.write("{\n")
a.write(" \"host\": \""+h+"\",\n")
a.write(" \"user\": \""+u+"\",\n")
a.write(" \"password\": \""+p+"\",\n")
a.write(" \"db\": \""+d+"\"\n")
a.write("}")
a.close()
